steps:
  - name: 'gcr.io/$PROJECT_ID/scala-sbt'
    args: ['test']
  - name: 'gcr.io/$PROJECT_ID/scala-sbt'
    args: ['docker:publishLocal']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'image', 'tag', 'us.gcr.io/broad-dsp-gcr-public/resource-validator:latest', 'us.gcr.io/broad-dsp-gcr-public/resource-validator:$SHORT_SHA']
images: [
    'us.gcr.io/broad-dsp-gcr-public/resource-validator:$SHORT_SHA',
    'us.gcr.io/broad-dsp-gcr-public/resource-validator:latest'
]