steps:
  - name: 'gcr.io/$PROJECT_ID/scala-sbt'
    args:
      - |
        testOnly -- -l cronJobs.dbTest; zombieMonitor/docker:publishLocal
    env:
      - 'JAVA_OPTS=-Xmx4G -Xms4G -Xss2M'
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'image', 'tag', 'us.gcr.io/broad-dsp-gcr-public/zombie-monitor:latest', 'us.gcr.io/broad-dsp-gcr-public/zombie-monitor:$SHORT_SHA']
images: [
    'us.gcr.io/broad-dsp-gcr-public/zombie-monitor:$SHORT_SHA',
    'us.gcr.io/broad-dsp-gcr-public/zombie-monitor:latest'
]