name: Create terra-helm Pull Request

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Set commit short hash
        id: setHash
        run: |
          echo $GITHUB_SHA
          git_short_sha=$(git rev-parse --short HEAD)
          echo $git_short_sha
          echo "::set-output name=git_short_sha::${git_short_sha}"
      - uses: marceloprado/has-changed-path@v1
        id: resource-validator
        with:
          paths: resource-validator core
      - uses: marceloprado/has-changed-path@v1
        id: zombie-monitor
        with:
          paths: zombie-monitor core
      - uses: actions/checkout@v2
        with:
          repository: broadinstitute/terra-helm
          ref: ci
      - name: update resource-validator hash
        uses: ./.github/actions/yq
        if: steps.resource-validator.outputs.changed == 'true'
        with:
          command: |
            yq w -i  charts/leonardo/values.yaml cronjob.imageTag ${{ steps.setHash.outputs.git_short_sha }}
      - name: update zombie-monitor hash
        uses: ./.github/actions/yq
        if: steps.zombie-monitor.outputs.changed == 'true'
        with:
          command: |
            yq w -i  charts/leonardo/values.yaml zombieMonitorCron.imageTag ${{ steps.setHash.outputs.git_short_sha }}
      - name: bump leonardo chart version
        if: ${{ steps.resource-validator.outputs.changed == 'true' || steps.zombie-monitor.outputs.changed == 'true' }}
        run: ./.github/scripts/bumpLeonardoChartVersion.sh
        shell: bash
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          commit-message: Update report
          committer: broadbot <broadbot@broadinstitute.org>
          author: broadbot <broadbot@broadinstitute.org>
          branch: resource-validator-version-bump
          delete-branch: true
          title: 'Bump leonardo cron jobs version'
          body: |
            Update leonardo cron jobs version.

            *This PR was opened by the [${{ github.workflow }} GitHub Actions workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).*
      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"