name: Create terra-helm Pull Request

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - uses: marceloprado/has-changed-path@v1
        id: resource-validator
        with:
          paths: resource-validator core
      - uses: marceloprado/has-changed-path@v1
        id: zombie-monitor
        with:
          paths: zombie-monitor core
      - uses: actions/checkout@v2
        with:
          repository: broadinstitute/terra-helm
      - name: update resource-validator hash
        if: steps.resource-validator.outputs.changed == 'true'
        run: .github/scripts/createCommit.sh resourceValidatorImageTag
        shell: bash
      - name: update zombie-monitor hash
        if: steps.zombie-monitor.outputs.changed == 'true'
        run: .github/scripts/createCommit.sh zombieMonitorImageTag
        shell: bash
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          commit-message: Update report
          committer: broadbot <broadbot@broadinstitute.org>
          author: broadbot <broadbot@broadinstitute.org>
          branch: resource-validator-version-bump
          delete-branch: true
          title: 'Bump resource validator version'
          body: |
            Update resource validator version.

            *This PR was opened by the [${{ github.workflow }} GitHub Actions workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).*
      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"