name: Create terra-helm Pull Request

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make changes to pull request
        run: |
          git clone https://github.com/broadinstitute/terra-helm
          git config user.name 'leonardo'
          git config user.email 'workbench-interactive-analysis@broadinstitute.org'
          cd terra-helm
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          sed -i "s/imageTag: .*/imageTag: $git_hash/g" charts/leonardo/values.yaml
          git add -am "bump version"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: patch
          delete-branch: true
          title: 'Bump resource validator version'
          draft: false

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"