name: Create terra-helm Pull Request

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: broadinstitute/terra-helm
      - name: Make changes to pull request
        run: |
          git config user.email "broadbot@broadinstitute.org"
          git config user.name "broadbot"
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          sed -i "s/resourceValidatorImageTag: .*/resourceValidatorImageTag: $git_hash/g" charts/leonardo/values.yaml
          sed -i "s/version: .*/version: $(date +"%m-%d-%y")/g" charts/leonardo/Chart.yaml
          git commit -am "bump version"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          commit-message: Update report
          committer: broadbot <broadbot@broadinstitute.org>
          author: broadbot <broadbot@broadinstitute.org>
          branch: patch
          delete-branch: true
          title: 'Bump resource validator version'

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"